2025-03-28 13:38:12,622 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133812-bs9io83g/logs/debug.log
2025-03-28 13:38:12,623 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133812-bs9io83g/logs/debug-internal.log
2025-03-28 13:38:12,623 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:38:12,623 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:38:12,623 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:38:14,114 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:38:14,114 INFO    MainThread:85338 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-28 13:38:48,601 INFO    MainThread:85338 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-28 13:38:48,618 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133848-hsxoqxo9/logs/debug.log
2025-03-28 13:38:48,618 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133848-hsxoqxo9/logs/debug-internal.log
2025-03-28 13:38:48,618 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:38:48,618 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:38:48,618 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:38:49,402 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:38:49,402 INFO    MainThread:85338 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-28 13:39:17,020 INFO    MainThread:85338 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-28 13:39:17,032 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133917-zbj9j2aq/logs/debug.log
2025-03-28 13:39:17,033 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133917-zbj9j2aq/logs/debug-internal.log
2025-03-28 13:39:17,033 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:39:17,033 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:39:17,033 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:39:17,867 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:39:17,868 INFO    MainThread:85338 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-28 13:39:43,985 INFO    MainThread:85338 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-28 13:39:43,994 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133943-wly2t6gd/logs/debug.log
2025-03-28 13:39:43,994 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_133943-wly2t6gd/logs/debug-internal.log
2025-03-28 13:39:43,994 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:39:43,994 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:39:43,994 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:41:09,071 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:41:09,073 INFO    MainThread:85338 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-28 13:42:06,709 INFO    MainThread:85338 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-28 13:42:06,718 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_134206-wefc3dd4/logs/debug.log
2025-03-28 13:42:06,718 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_134206-wefc3dd4/logs/debug-internal.log
2025-03-28 13:42:06,719 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:42:06,719 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:42:06,719 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:43:29,424 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:43:29,425 INFO    MainThread:85338 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-28 13:44:09,842 INFO    MainThread:85338 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-28 13:44:09,851 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_134409-izoqmfvz/logs/debug.log
2025-03-28 13:44:09,851 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_134409-izoqmfvz/logs/debug-internal.log
2025-03-28 13:44:09,851 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 13:44:09,851 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 13:44:09,851 INFO    MainThread:85338 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-28 13:45:47,127 INFO    MainThread:85338 [wandb_run.py:_finish():2112] finishing run vedanshiib-brandeis-university/sepsis-ehr-analysis/l3nqkm7k
2025-03-28 13:45:47,132 INFO    MainThread:85338 [jupyter.py:save_history():458] not saving jupyter history
2025-03-28 13:45:47,132 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 13:45:47,132 INFO    MainThread:85338 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-28 13:45:47,133 INFO    MainThread:85338 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-03-28 13:45:47,133 INFO    MainThread:85338 [wandb_run.py:_restore():2322] restore
2025-03-28 13:45:47,134 INFO    MainThread:85338 [wandb_run.py:_restore():2328] restore done
2025-03-28 13:45:47,718 INFO    MainThread:85338 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-28 13:45:47,719 INFO    MainThread:85338 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-28 13:45:47,719 INFO    MainThread:85338 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-28 14:49:14,284 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_144914-ch0wkymu/logs/debug.log
2025-03-28 14:49:14,286 INFO    MainThread:85338 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/vedanshi/Documents/GitHub/practical-ml-project-2/wandb/run-20250328_144914-ch0wkymu/logs/debug-internal.log
2025-03-28 14:49:14,286 INFO    MainThread:85338 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x130fa9d00>
2025-03-28 14:49:14,287 INFO    MainThread:85338 [wandb_init.py:init():761] calling init triggers
2025-03-28 14:49:14,287 INFO    MainThread:85338 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-28 14:49:14,287 INFO    MainThread:85338 [wandb_init.py:init():784] starting backend
2025-03-28 14:49:14,287 INFO    MainThread:85338 [wandb_init.py:init():788] sending inform_init request
2025-03-28 14:49:14,289 INFO    MainThread:85338 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-28 14:49:14,289 INFO    MainThread:85338 [wandb_init.py:init():798] backend started and connected
2025-03-28 14:49:14,293 INFO    MainThread:85338 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-28 14:49:14,294 INFO    MainThread:85338 [wandb_init.py:init():891] updated telemetry
2025-03-28 14:49:14,326 INFO    MainThread:85338 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-28 14:49:14,657 INFO    MainThread:85338 [wandb_init.py:init():990] starting run threads in backend
2025-03-28 14:49:15,004 INFO    MainThread:85338 [wandb_run.py:_console_start():2375] atexit reg
2025-03-28 14:49:15,004 INFO    MainThread:85338 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-28 14:49:15,004 INFO    MainThread:85338 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-28 14:49:15,005 INFO    MainThread:85338 [wandb_run.py:_redirect():2315] Redirects installed.
2025-03-28 14:49:15,005 INFO    MainThread:85338 [wandb_init.py:init():1032] run started, returning control to user process
2025-03-28 14:49:31,055 INFO    MainThread:85338 [wandb_run.py:_finish():2112] finishing run vedanshiib-brandeis-university/sepsis-ehr-analysis/ch0wkymu
2025-03-28 14:49:31,058 INFO    MainThread:85338 [jupyter.py:save_history():458] not saving jupyter history
2025-03-28 14:49:31,058 INFO    MainThread:85338 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-28 14:49:31,058 INFO    MainThread:85338 [wandb_init.py:_jupyter_teardown():581] cleaning up jupyter logic
2025-03-28 14:49:31,058 INFO    MainThread:85338 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-03-28 14:49:31,059 INFO    MainThread:85338 [wandb_run.py:_restore():2322] restore
2025-03-28 14:49:31,059 INFO    MainThread:85338 [wandb_run.py:_restore():2328] restore done
2025-03-28 14:49:31,685 INFO    MainThread:85338 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-03-28 14:49:31,685 INFO    MainThread:85338 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-03-28 14:49:31,685 INFO    MainThread:85338 [wandb_run.py:_footer_sync_info():3917] logging synced files
2025-03-28 15:12:18,862 WARNING MsgRouterThr:85338 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/anaconda3/envs/test_env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-28 15:12:18,868 INFO    MsgRouterThr:85338 [mailbox.py:close():129] Closing mailbox, abandoning 2 handles.
